# Generated by Django 4.0.2 on 2022-02-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pidrov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('tema', models.CharField(max_length=32)),
                ('info', models.TextField()),
                ('created_at', models.DateField()),
            ],
            options={
                'verbose_name': 'Новость про Пидора',
                'verbose_name_plural': 'Новости про Пидораcов',
            },
        ),
    ]
